# -*- coding: utf-8 -*-
"""Movies.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BmH03bU6cS9NuBPAFJo2K_dYDLZIn5Yg
"""

import pandas as pd
import streamlit as st

import zipfile

with zipfile.ZipFile('/content/ml-latest-small.zip', 'r') as z:
    z.extractall('/content/')

DATA_DIR='/content/ml-latest-small/'
movies=pd.read_csv(DATA_DIR+'movies.csv')
ratings=pd.read_csv(DATA_DIR+'ratings.csv')
tags=pd.read_csv(DATA_DIR+'tags.csv')
links=pd.read_csv(DATA_DIR+'links.csv')

movies.head()

movies['genres_clean']=movies['genres'].str.replace('|',' ',regex=False)
movies['year']=movies['title'].str.extract(r'\((\d{4})\)$').astype(float)
movies['title'] = movies['title'].str.replace(r'\s*\(\d{4}\)$', '', regex=True).str.strip()

movies.head()

ratings.head()

ratings['rated_at']=pd.to_datetime(ratings['timestamp'],unit='s')

ratings.head()

tags.head()

tags['tagged_at']=pd.to_datetime(tags['timestamp'],unit='s')
tags=tags.drop(columns=['timestamp'])

tags.head()

avg_ratings=(ratings.groupby('movieId')['rating'].agg(rating='mean',num_ratings="count").round(2).reset_index())

movie_tags = (
    tags
    .groupby('movieId')['tag']
    .apply(lambda x: ' '.join(x))
    .reset_index()
    .rename(columns={'tag': 'tags'})
)

df = movies.merge(avg_ratings, on='movieId', how='left')
df = df.merge(movie_tags,  on='movieId', how='left')

df['rating']= df['rating'].fillna(0.0)
df['num_ratings']= df['num_ratings'].fillna(0).astype(int)
df['tags']= df['tags'].fillna('')
df["soup"]=df['genres_clean']+" "+df["tags"]

df.head()

from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(df['soup'])
sim_matrix = cosine_similarity(tfidf_matrix, tfidf_matrix)

print("TF-IDF matrix shape:", tfidf_matrix.shape)
print("Similarity matrix shape:", sim_matrix.shape)

movie_title = "Toy Story"
idx = df[df['title'] == movie_title].index[0]
print("Movie found at index:", idx)

scores=list(enumerate(sim_matrix[idx]))
print("Sample scores",scores[:5])

scores=sorted(scores,key=lambda x:x[1],reverse=True)
print("Top 10 similar movies and scores")
scores = [(i, s) for i, s in scores if i != idx][:10]

result_idx=[i[0] for i in scores]
recommendations=df.iloc[result_idx][['title','genres','rating']].copy()
recommendations['similarity']=[round(s[1],3) for s in scores]
recomendations=recommendations.sort_values(['similarity','rating'],ascending=[False,False],inplace=True)
recommendations.reset_index(drop=True,inplace=True)
recommendations

all_genres = sorted(set(
    genre
    for genres in df['genres'].dropna()
    for genre in genres.split('|')
    if genre != '(no genres listed)'
))

print("All available genres:")
print(all_genres)

selected_genres = ['Animation', 'Comedy']
min_rating      = 3.0
max_rating      = 5.0
min_votes       = 50


filtered_df = df.copy()


if selected_genres:
    mask = filtered_df['genres'].apply(
        lambda g: any(genre in str(g) for genre in selected_genres)
    )
    filtered_df = filtered_df[mask]

filtered_df = filtered_df[filtered_df['rating'].between(min_rating, max_rating)]

filtered_df = filtered_df[filtered_df['num_ratings'] >= min_votes]

filtered_df = filtered_df.reset_index(drop=True)

print(f"Movies after filtering: {len(filtered_df)}")
filtered_df[['title', 'genres', 'rating', 'num_ratings']].head(10)

movie_title = "Toy Story"


if movie_title not in filtered_df['title'].values:
    print(f"'{movie_title}' not in filtered results. Try different filters.")
else:

    idx = df[df['title'] == movie_title].index[0]
    scores = list(enumerate(sim_matrix[idx]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)

    filtered_indices = set(filtered_df.index)
    scores = [(i, s) for i, s in scores if i in filtered_indices and i != idx][:10]

    result_idx = [i[0] for i in scores]
    recommendations = df.iloc[result_idx][['title', 'genres', 'rating', 'num_ratings']].copy()
    recommendations['similarity'] = [round(s[1], 3) for s in scores]

    recommendations.sort_values(
        ['similarity', 'rating'],
        ascending=[False, False],
        inplace=True
    )
    recommendations.reset_index(drop=True, inplace=True)
    recommendations

import streamlit as st
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import plotly.express as px
import zipfile
import os

st.set_page_config(page_title="Movie Recommender", layout="wide")
st.title("Movie Recommender")

@st.cache_data
def load_data():
    movies  = pd.read_csv('movies.csv')
    ratings = pd.read_csv('ratings.csv')
    tags    = pd.read_csv('tags.csv')


    movies['genres_clean'] = movies['genres'].str.replace('|', ' ', regex=False)
    movies['title'] = movies['title'].str.replace(r'\s*\(\d{4}\)$', '', regex=True).str.strip()
    movies= movies.dropna(subset=['title'])

    avg_ratings = (
        ratings
        .groupby('movieId')['rating']
        .agg(rating='mean', num_ratings='count')
        .round(2)
        .reset_index()
    )

    movie_tags = (
        tags
        .groupby('movieId')['tag']
        .apply(lambda x: ' '.join(x))
        .reset_index()
        .rename(columns={'tag': 'tags'})
    )

    df = movies.merge(avg_ratings, on='movieId', how='left')
    df = df.merge(movie_tags, on='movieId', how='left')
    df['rating']      = df['rating'].fillna(0.0)
    df['num_ratings'] = df['num_ratings'].fillna(0).astype(int)
    df['tags']        = df['tags'].fillna('')
    df['soup']        = df['genres_clean'] + ' ' + df['tags']

    return df

@st.cache_data
def build_sim_matrix(df):
    tfidf  = TfidfVectorizer(stop_words='english')
    matrix = tfidf.fit_transform(df['soup'])
    return cosine_similarity(matrix, matrix)

df         = load_data()
sim_matrix = build_sim_matrix(df)

if 'liked' not in st.session_state:
    st.session_state.liked = []

st.sidebar.header("Filters")

all_genres = sorted(set(
    g for genres in df['genres'].dropna()
    for g in genres.split('|')
    if g != '(no genres listed)'
))

selected_genres = st.sidebar.multiselect("Genres", all_genres)
min_r, max_r    = st.sidebar.slider("Rating", 0.0, 5.0, (3.0, 5.0), step=0.5)
min_votes       = st.sidebar.slider("Min votes", 0, 500, 50, step=10)

filtered_df = df.copy()
if selected_genres:
    filtered_df = filtered_df[filtered_df['genres'].apply(
        lambda g: any(x in str(g) for x in selected_genres)
    )]
filtered_df = filtered_df[filtered_df['rating'].between(min_r, max_r)]
filtered_df = filtered_df[filtered_df['num_ratings'] >= min_votes]
filtered_df = filtered_df.reset_index(drop=True)
st.sidebar.write(f"{len(filtered_df)} movies found")

tab1, tab2, tab3 = st.tabs(["Recommend", "Liked List", "Charts"])

with tab1:
    st.subheader("Pick a movie you like")
    movie = st.selectbox("Choose a movie", options=sorted(filtered_df['title'].dropna().unique()))
    n     = st.slider("Number of recommendations", 5, 20, 10)

    if st.button("Get recommendations"):
        idx    = df[df['title'] == movie].index[0]
        scores = sorted(enumerate(sim_matrix[idx]), key=lambda x: x[1], reverse=True)
        scores = [(i, s) for i, s in scores if i != idx][:n]

        recs = df.iloc[[i[0] for i in scores]][['title', 'genres', 'rating', 'num_ratings']].copy()
        recs['similarity'] = [round(s[1], 3) for s in scores]
        recs.sort_values(['similarity', 'rating'], ascending=[False, False], inplace=True)
        recs.reset_index(drop=True, inplace=True)

        st.success(f"Top {n} movies similar to '{movie}'")
        st.dataframe(recs, use_container_width=True)

        st.subheader("Like any of these?")
        for _, row in recs.iterrows():
            c1, c2, c3 = st.columns([3, 1, 1])
            c1.write(f"**{row['title']}** — {row['genres']}")
            c2.write(f"Rated {row['rating']}")
            if c3.button("Like", key=f"like_{row['title']}"):
                if row['title'] not in st.session_state.liked:
                    st.session_state.liked.append(row['title'])
                    st.toast(f"Added: {row['title']}")

with tab2:
    st.subheader("Your liked movies")
    if not st.session_state.liked:
        st.info("No liked movies yet. Browse and like some!")
    else:
        for m in st.session_state.liked:
            c1, c2 = st.columns([4, 1])
            c1.write(m)
            if c2.button("Remove", key=f"remove_{m}"):
                st.session_state.liked.remove(m)
                st.rerun()
        if st.button("Clear all"):
            st.session_state.liked = []
            st.rerun()

with tab3:
    st.subheader("Genre distribution")
    genre_counts = (
        filtered_df['genres']
        .str.split('|')
        .explode()
        .value_counts()
        .reset_index()
    )
    genre_counts.columns = ['genre', 'count']
    fig = px.bar(
        genre_counts.head(15),
        x='genre', y='count',
        title="Top 15 genres",
        color='count',
        color_continuous_scale='teal'
    )
    st.plotly_chart(fig, use_container_width=True)

    st.subheader("Rating distribution")
    fig2 = px.histogram(
        filtered_df[filtered_df['rating'] > 0],
        x='rating', nbins=20,
        title="How are ratings spread?"
    )
    st.plotly_chart(fig2, use_container_width=True)

from google.colab import files
files.download('/content/app.py')

